apiVersion: apps/v1
kind: Deployment
metadata:
  name: humix-srv-teste
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: humix-srv-teste
  template:
    metadata:
      labels:
        app: humix-srv-teste
    spec:
      containers:
      - name: humix-srv-teste
        image: imagem
        ports:
        - containerPort: 8080
        env:
          - name: DB_HOST
            value: "ep-frosty-glade-a4hleumr-pooler.us-east-1.aws.neon.tech"
          - name: DB_PORT
            value: "5432"
          - name: DB_USER
            value: "neondb_owner"
          - name: DB_PASS
            value: "npg_DyGwIg7J2oBV"
          - name: DB_NAME
            value: "neondb"
          - name: JWT_TOKEN
            value: "jwt-humix-token"

