apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: teste

images:
- name: imagem
  newName: blgianini/humix
  newTag: cd3c13ce55be07d43cadb6de401b18f63a9c67c4
