apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: teste

images:
- name: imagem
  newName: blgianini/humix
  newTag: 88fcd64be1a071c69d24afbebf8926e8b27b7370
